export enum Stage {
  FINAL = "FINAL",
  THIRD_PLACE = "THIRD_PLACE",
  SEMI_FINALS = "SEMI_FINALS",
  QUARTER_FINALS = "QUARTER_FINALS",
  LAST_16 = "LAST_16",
  LAST_32 = "LAST_32",
  LAST_64 = "LAST_64",
  ROUND_4 = "ROUND_4",
  ROUND_3 = "ROUND_3",
  ROUND_2 = "ROUND_2",
  ROUND_1 = "ROUND_1",
  GROUP_STAGE = "GROUP_STAGE",
  PRELIMINARY_ROUND = "PRELIMINARY_ROUND",
  QUALIFICATION = "QUALIFICATION",
  QUALIFICATION_ROUND_1 = "QUALIFICATION_ROUND_1",
  QUALIFICATION_ROUND_2 = "QUALIFICATION_ROUND_2",
  QUALIFICATION_ROUND_3 = "QUALIFICATION_ROUND_3",
  PLAYOFF_ROUND_1 = "PLAYOFF_ROUND_1",
  PLAYOFF_ROUND_2 = "PLAYOFF_ROUND_2",
  PLAYOFFS = "PLAYOFFS",
  REGULAR_SEASON = "REGULAR_SEASON",
  CLAUSURA = "CLAUSURA",
  APERTURA = "APERTURA",
  CHAMPIONSHIP = "CHAMPIONSHIP",
  RELEGATION = "RELEGATION",
  RELEGATION_ROUND = "RELEGATION_ROUND",
}

export const stageLabels: Record<Stage, string> = {
  [Stage.FINAL]: "Final",
  [Stage.THIRD_PLACE]: "Third Place",
  [Stage.SEMI_FINALS]: "Semi Finals",
  [Stage.QUARTER_FINALS]: "Quarter Finals",
  [Stage.LAST_16]: "Last 16",
  [Stage.LAST_32]: "Last 32",
  [Stage.LAST_64]: "Last 64",
  [Stage.ROUND_4]: "Round 4",
  [Stage.ROUND_3]: "Round 3",
  [Stage.ROUND_2]: "Round 2",
  [Stage.ROUND_1]: "Round 1",
  [Stage.GROUP_STAGE]: "Group Stage",
  [Stage.PRELIMINARY_ROUND]: "Preliminary Round",
  [Stage.QUALIFICATION]: "Qualification",
  [Stage.QUALIFICATION_ROUND_1]: "Qualification Round 1",
  [Stage.QUALIFICATION_ROUND_2]: "Qualification Round 2",
  [Stage.QUALIFICATION_ROUND_3]: "Qualification Round 3",
  [Stage.PLAYOFF_ROUND_1]: "Playoff Round 1",
  [Stage.PLAYOFF_ROUND_2]: "Playoff Round 2",
  [Stage.PLAYOFFS]: "Playoffs",
  [Stage.REGULAR_SEASON]: "Regular Season",
  [Stage.CLAUSURA]: "Clausura",
  [Stage.APERTURA]: "Apertura",
  [Stage.CHAMPIONSHIP]: "Championship",
  [Stage.RELEGATION]: "Relegation",
  [Stage.RELEGATION_ROUND]: "Relegation Round",
};

export const getStageLabel = (stage: Stage): string => stageLabels[stage];
